default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 3306

development:
  <<: *default
  database: bad_sns_development

test:
  <<: *default
  database: bad_sns_test

production:
  <<: *default
  database: bad_sns_production
